apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-deployment
  labels:
    name: workshop-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: workshop-web
  template:
    metadata:
      labels:
        name: workshop-web
    spec:
      containers:
      - name: workshop-web
        image: dockerweb-image:v2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: workshop-web
  labels:
    name: workshop-web
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    name: workshop-web
